def generate_markdown(sector, analysis):

    markdown = f"""
# {sector.capitalize()} Sector Trade Analysis

## AI Market Analysis

{analysis}

---
*Generated by Trade Opportunities API*
"""

    return markdown